CREATE OR REPLACE FUNCTION DELETE_ALL_PRODUCTS_FROM_DB
RETURN NUMBER AS
  deleted_rows NUMBER;
  
BEGIN

  DELETE FROM PRODUCT;
  deleted_rows := SQL%ROWCOUNT;
  COMMIT;

  RETURN deleted_rows;
  
EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20000, SQLERRM);
END DELETE_ALL_PRODUCTS_FROM_DB;
/

CREATE OR REPLACE PROCEDURE DELETE_ALL_PRODUCTS_VIASQLDEV
AS
  deleted_rows NUMBER;
  
BEGIN
 DBMS_OUTPUT.PUT_LINE('------------------------------');
 DBMS_OUTPUT.PUT_LINE('Deleting all Products rows');
 
 deleted_rows := DELETE_ALL_PRODUCTS_FROM_DB;
 
  DBMS_OUTPUT.PUT_LINE(deleted_rows || ' rows deleted');

EXCEPTION
  WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE(SQLERRM);
  
END DELETE_ALL_PRODUCTS_VIASQLDEV;
/