CREATE OR REPLACE FUNCTION GET_PROD_STRING_FROM_DB (
    pprodid NUMBER
)
RETURN VARCHAR2
AS
    name VARCHAR2(50);
    price NUMBER(10, 2);
    sales_ytd NUMBER(10, 2);

BEGIN
    SELECT PRODUCT.PRODNAME, PRODUCT.SELLING_PRICE, PRODUCT.SALES_YTD
    INTO name, price, sales_ytd
    FROM PRODUCT
    WHERE PRODUCT.PRODID = pprodid;

    RETURN 'Prodid: ' || pprodid || ' Name: ' || name || ' Price: ' || TO_CHAR(price, '999.99') || ' SalesYTD: ' || TO_CHAR(sales_ytd, '99999.99');

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20091, 'Product ID not found');
    
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20000,SQLERRM);
END GET_PROD_STRING_FROM_DB;
/

CREATE OR REPLACE PROCEDURE GET_PROD_STRING_VIASQLDEV (
    pprodid NUMBER
)
AS
BEGIN
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('Getting Details for Prod Id ' || pprodid);
    DBMS_OUTPUT.PUT_LINE(GET_PROD_STRING_FROM_DB(pprodid));

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END GET_PROD_STRING_VIASQLDEV;
/