CREATE OR REPLACE FUNCTION SUM_PROD_SALESYTD_FROM_DB
RETURN NUMBER
AS
    total_sales NUMBER;
BEGIN
    SELECT NVL(SUM(SALES_YTD), 0) INTO total_sales FROM PRODUCT;
    RETURN total_sales;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20000, 'Error: ' || SQLERRM);
END SUM_PROD_SALESYTD_FROM_DB;
/

CREATE OR REPLACE PROCEDURE SUM_PROD_SALES_VIASQLDEV
AS
    total_sales NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('Summing Product SalesYTD');

    total_sales := SUM_PROD_SALESYTD_FROM_DB;

    DBMS_OUTPUT.PUT_LINE('All Product Total: ' || TO_CHAR(total_sales, '99999.99'));
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END SUM_PROD_SALES_VIASQLDEV;
/