-- Insert sample data into CUSTOMER table
INSERT INTO CUSTOMER (CUSTID, CUSTNAME, SALES_YTD, STATUS) 
VALUES (1, 'John Doe', 1000, 'OK');
INSERT INTO CUSTOMER (CUSTID, CUSTNAME, SALES_YTD, STATUS)
VALUES (2, 'Jane Smith', 500, 'OK');
INSERT INTO CUSTOMER (CUSTID, CUSTNAME, SALES_YTD, STATUS)
VALUES (3, 'Alice Johnson', 1200, 'SUSPEND');
INSERT INTO CUSTOMER (CUSTID, CUSTNAME, SALES_YTD, STATUS)
VALUES (4, 'Bob Brown', 0, 'OK');

-- Insert sample data into PRODUCT table
INSERT INTO PRODUCT (PRODID, PRODNAME, SELLING_PRICE, SALES_YTD) 
VALUES (1001, 'Laptop', 1200.00, 2400.00);
INSERT INTO PRODUCT (PRODID, PRODNAME, SELLING_PRICE, SALES_YTD) 
VALUES (1002, 'Smartphone', 800.00, 1600.00);
INSERT INTO PRODUCT (PRODID, PRODNAME, SELLING_PRICE, SALES_YTD) 
VALUES (1003, 'Tablet', 400.00, 800.00);
INSERT INTO PRODUCT (PRODID, PRODNAME, SELLING_PRICE, SALES_YTD)
VALUES (1004, 'Headphones', 150.00, 300.00);

-- Insert sample data into SALE table
INSERT INTO SALE (SALEID, CUSTID, PRODID, QTY, PRICE, SALEDATE) 
VALUES (1, 1, 1001, 1, 1200.00, SYSDATE);
INSERT INTO SALE (SALEID, CUSTID, PRODID, QTY, PRICE, SALEDATE) 
VALUES (2, 2, 1002, 2, 1600.00, SYSDATE);
INSERT INTO SALE (SALEID, CUSTID, PRODID, QTY, PRICE, SALEDATE) 
VALUES (3, 3, 1003, 1, 400.00, SYSDATE);
INSERT INTO SALE (SALEID, CUSTID, PRODID, QTY, PRICE, SALEDATE) 
VALUES (4, 1, 1004, 2, 300.00, SYSDATE);

-- Insert sample data into LOCATION table
INSERT INTO LOCATION (LOCID, MINQTY, MAXQTY)
VALUES ('LOC01', 10, 100);
INSERT INTO LOCATION (LOCID, MINQTY, MAXQTY)
VALUES ('LOC02', 20, 200);
INSERT INTO LOCATION (LOCID, MINQTY, MAXQTY)
VALUES ('LOC03', 15, 150);
INSERT INTO LOCATION (LOCID, MINQTY, MAXQTY)
VALUES ('LOC04', 30, 300);

COMMIT;
